arrowParens: "always"
bracketSameLine: false
bracketSpacing: true
embeddedLanguageFormatting: "auto"
htmlWhitespaceSensitivity: "ignore"
insertPragma: false
jsxSingleQuote: false
printWidth: 100
proseWrap: "preserve"
quoteProps: "as-needed"
requirePragma: false
semi: true
singleQuote: false
tabWidth: 2
trailingComma: "es5"
useTabs: false
vueIndentScriptAndStyle: false
endOfLine: "auto"
overrides:
  - files: "*.html"
    options:
      parser: "html"
