export const useCountryTypes = () => {
  return [
    { value: "AD", name: "安道爾 Andorra" },
    { value: "AE", name: "阿拉伯聯合大公國 United Arab Emirates" },
    { value: "AF", name: "阿富汗 Afghanistan" },
    { value: "AG", name: "安地卡巴布達 Antigua and Barbuda" },
    { value: "AI", name: "安圭拉 Anguilla" },
    { value: "AL", name: "阿爾巴尼亞 Albania" },
    { value: "AM", name: "亞美尼亞 Armenia" },
    { value: "AN", name: "荷屬安地列斯 Netherlands Antilles" },
    { value: "AO", name: "安哥拉 Angola" },
    { value: "AQ", name: "南極洲 Antarctica" },
    { value: "AR", name: "阿根廷 Argentina" },
    { value: "AS", name: "美屬薩摩亞 American Samoa" },
    { value: "AT", name: "奧地利 Austria" },
    { value: "AU", name: "澳大利亞 Australia" },
    { value: "AW", name: "阿魯巴 Aruba" },
    { value: "AX", name: "奧蘭群島 Åland Islands" },
    { value: "AZ", name: "亞塞拜然 Azerbaijan" },
    { value: "BA", name: "波士尼亞赫塞哥維納 Bosnia and Herzegovina" },
    { value: "BB", name: "巴貝多 Barbados" },
    { value: "BD", name: "孟加拉 Bangladesh" },
    { value: "BE", name: "比利時 Belgium" },
    { value: "BF", name: "布吉納法索 Burkina Faso" },
    { value: "BG", name: "保加利亞 Bulgaria" },
    { value: "BH", name: "巴林 Bahrain" },
    { value: "BI", name: "蒲隆地 Burundi" },
    { value: "BJ", name: "貝南 Benin" },
    { value: "BM", name: "百慕達 Bermuda" },
    { value: "BN", name: "汶萊 Brunei Darussalam" },
    { value: "BO", name: "玻利維亞 Bolivia" },
    { value: "BR", name: "巴西 Brazil" },
    { value: "BS", name: "巴哈馬 Bahamas" },
    { value: "BT", name: "不丹 Bhutan" },
    { value: "BV", name: "波維特島 Bouvet Island" },
    { value: "BW", name: "波札那 Botswana" },
    { value: "BY", name: "白俄羅斯 Belarus" },
    { value: "BZ", name: "貝里斯 Belize" },
    { value: "CA", name: "加拿大 Canada" },
    { value: "CC", name: "可可斯群島 Cocos (Keeling) Islands" },
    { value: "CD", name: "剛果民主共和國 The Democratic Republic of The Congo" },
    { value: "CF", name: "中非共和國 Central African Republic" },
    { value: "CG", name: "剛果 Congo" },
    { value: "CH", name: "瑞士 Switzerland" },
    { value: "CI", name: "象牙海岸 Côte D'Ivoire" },
    { value: "CK", name: "庫克群島 Cook Islands" },
    { value: "CL", name: "智利 Chile" },
    { value: "CM", name: "喀麥隆 Cameroon" },
    { value: "CN", name: "中國 China" },
    { value: "CO", name: "哥倫比亞 Colombia" },
    { value: "CR", name: "哥斯大黎加 Costa Rica" },
    { value: "CU", name: "古巴 Cuba" },
    { value: "CV", name: "維德角 Cape Verde" },
    { value: "CX", name: "聖誕島 Christmas Island" },
    { value: "CY", name: "賽普勒斯 Cyprus" },
    { value: "CZ", name: "捷克 Czech Republic" },
    { value: "DE", name: "德國 Germany" },
    { value: "DJ", name: "吉布地 Djibouti" },
    { value: "DK", name: "丹麥 Denmark" },
    { value: "DM", name: "多米尼克 Dominica" },
    { value: "DO", name: "多明尼加 Dominican Republic" },
    { value: "DZ", name: "阿爾及利亞 Algeria" },
    { value: "EC", name: "厄瓜多 Ecuador" },
    { value: "EE", name: "愛沙尼亞 Estonia" },
    { value: "EG", name: "埃及 Egypt" },
    { value: "EH", name: "西撒哈拉 Western Sahara" },
    { value: "ER", name: "厄利垂亞 Eritrea" },
    { value: "ES", name: "西班牙 Spain" },
    { value: "ET", name: "衣索比亞 Ethiopia" },
    { value: "FI", name: "芬蘭 Finland" },
    { value: "FJ", name: "斐濟 Fiji" },
    { value: "FK", name: "福克蘭群島 Falkland Islands (Malvinas)" },
    { value: "FM", name: "密克羅尼西亞聯邦 Federated States of Micronesia" },
    { value: "FO", name: "法羅群島 Faroe Islands" },
    { value: "FR", name: "法國 France" },
    { value: "GA", name: "加彭 Gabon" },
    { value: "GB", name: "英國 United Kingdom" },
    { value: "GD", name: "格瑞那達 Grenada" },
    { value: "GE", name: "喬治亞 Georgia" },
    { value: "GF", name: "法屬圭亞那 French Guiana" },
    { value: "GG", name: "根息 Guernsey" },
    { value: "GH", name: "迦納 Ghana" },
    { value: "GI", name: "直布羅陀 Gibraltar" },
    { value: "GL", name: "格陵蘭 Greenland" },
    { value: "GM", name: "甘比亞 Gambia" },
    { value: "GN", name: "幾內亞 Guinea" },
    { value: "GP", name: "哥德洛普 Guadeloupe" },
    { value: "GQ", name: "赤道幾內亞 Equatorial Guinea" },
    { value: "GR", name: "希臘 Greece" },
    { value: "GS", name: "南喬治亞南桑威奇群島 South Georgia and The South Sandwich Islands" },
    { value: "GT", name: "瓜地馬拉 Guatemala" },
    { value: "GU", name: "關島 Guam" },
    { value: "GW", name: "幾內亞比索 Guinea-Bissau" },
    { value: "GY", name: "蓋亞那 Guyana" },
    { value: "HK", name: "香港 Hong Kong" },
    { value: "HM", name: "赫德麥當勞群島 Heard Island and Mcdonald Islands" },
    { value: "HN", name: "宏都拉斯 Honduras" },
    { value: "HR", name: "克羅埃西亞 Croatia" },
    { value: "HT", name: "海地 Haiti" },
    { value: "HU", name: "匈牙利 Hungary" },
    { value: "ID", name: "印尼 Indonesia" },
    { value: "IE", name: "愛爾蘭 Ireland" },
    { value: "IL", name: "以色列 Israel" },
    { value: "IM", name: "曼島 Isle of Man" },
    { value: "IN", name: "印度 India" },
    { value: "IO", name: "英屬印度洋地區 British Indian Ocean Territory" },
    { value: "IQ", name: "伊拉克 Iraq" },
    { value: "IR", name: "伊朗 Islamic Republic of Iran" },
    { value: "IS", name: "冰島 Iceland" },
    { value: "IT", name: "義大利 Italy" },
    { value: "JE", name: "澤西 Jersey" },
    { value: "JM", name: "牙買加 Jamaica" },
    { value: "JO", name: "約旦 Jordan" },
    { value: "JP", name: "日本 Japan" },
    { value: "KE", name: "肯亞 Kenya" },
    { value: "KG", name: "吉爾吉斯 Kyrgyzstan" },
    { value: "KH", name: "柬埔寨 Cambodia" },
    { value: "KI", name: "吉里巴斯 Kiribati" },
    { value: "KM", name: "葛摩 Comoros" },
    { value: "KN", name: "聖克里斯多福 Saint Kitts and Nevis" },
    { value: "KP", name: "北韓 Democratic People's Republic of Korea" },
    { value: "KR", name: "南韓 Republic of Korea" },
    { value: "KW", name: "科威特 Kuwait" },
    { value: "KY", name: "開曼群島 Cayman Islands" },
    { value: "KZ", name: "哈薩克 Kazakhstan" },
    { value: "LA", name: "寮國 Lao People's Democratic Republic" },
    { value: "LB", name: "黎巴嫩 Lebanon" },
    { value: "LC", name: "聖露西亞 Saint Lucia" },
    { value: "LI", name: "列支敦斯登 Liechtenstein" },
    { value: "LK", name: "斯里蘭卡 Sri Lanka" },
    { value: "LR", name: "賴比瑞亞 Liberia" },
    { value: "LS", name: "賴索托 Lesotho" },
    { value: "LT", name: "立陶宛 Lithuania" },
    { value: "LU", name: "盧森堡 Luxembourg" },
    { value: "LV", name: "拉脫維亞 Latvia" },
    { value: "LY", name: "利比亞 Libyan Arab Jamahiriya" },
    { value: "MA", name: "摩洛哥 Morocco" },
    { value: "MC", name: "摩納哥 Monaco" },
    { value: "MD", name: "摩爾多瓦 Republic of Moldova" },
    { value: "ME", name: "蒙特內哥羅 Montenegro" },
    { value: "MG", name: "馬達加斯加 Madagascar" },
    { value: "MH", name: "馬紹爾群島 Marshall Islands" },
    { value: "MK", name: "馬其頓 Republic of Macedonia" },
    { value: "ML", name: "馬利 Mali" },
    { value: "MM", name: "緬甸 Myanmar" },
    { value: "MN", name: "蒙古 Mongolia" },
    { value: "MO", name: "澳門 Macao" },
    { value: "MP", name: "北馬里亞納群島 Northern Mariana Islands" },
    { value: "MQ", name: "馬丁尼克 Martinique" },
    { value: "MR", name: "茅利塔尼亞 Mauritania" },
    { value: "MS", name: "蒙特色拉 Montserrat" },
    { value: "MT", name: "馬爾他 Malta" },
    { value: "MU", name: "模里西斯 Mauritius" },
    { value: "MV", name: "馬爾地夫 Maldives" },
    { value: "MW", name: "馬拉威 Malawi" },
    { value: "MX", name: "墨西哥 Mexico" },
    { value: "MY", name: "馬來西亞 Malaysia" },
    { value: "MZ", name: "莫三比克 Mozambique" },
    { value: "NA", name: "納米比亞 Namibia" },
    { value: "NC", name: "新喀里多尼亞 New Caledonia" },
    { value: "NE", name: "尼日 Niger" },
    { value: "NF", name: "諾福克島 Norfolk Island" },
    { value: "NG", name: "奈及利亞 Nigeria" },
    { value: "NI", name: "尼加拉瓜 Nicaragua" },
    { value: "NL", name: "荷蘭 Netherlands" },
    { value: "NO", name: "挪威 Norway" },
    { value: "NP", name: "尼泊爾 Nepal" },
    { value: "NR", name: "諾魯 Nauru" },
    { value: "NU", name: "紐埃 Niue" },
    { value: "NZ", name: "紐西蘭 New Zealand" },
    { value: "OM", name: "阿曼 Oman" },
    { value: "PA", name: "巴拿馬 Panama" },
    { value: "PE", name: "秘魯 Peru" },
    { value: "PF", name: "法屬波里尼西亞 French Polynesia" },
    { value: "PG", name: "巴布亞紐幾內亞 Papua New Guinea" },
    { value: "PH", name: "菲律賓 Philippines" },
    { value: "PK", name: "巴基斯坦 Pakistan" },
    { value: "PL", name: "波蘭 Poland" },
    { value: "PM", name: "聖皮耶密克隆 Saint Pierre and Miquelon" },
    { value: "PN", name: "皮特康 Pitcairn" },
    { value: "PR", name: "波多黎各 Puerto Rico" },
    { value: "PS", name: "巴勒斯坦 Palestinian Territory, Occupied" },
    { value: "PT", name: "葡萄牙 Portugal" },
    { value: "PW", name: "帛琉 Palau" },
    { value: "PY", name: "巴拉圭 Paraguay" },
    { value: "QA", name: "卡達 Qatar" },
    { value: "RE", name: "留尼旺 Réunion" },
    { value: "RO", name: "羅馬尼亞 Romania" },
    { value: "RS", name: "塞爾維亞 Serbia" },
    { value: "RU", name: "俄羅斯 Russian Federation" },
    { value: "RW", name: "盧安達 Rwanda" },
    { value: "SA", name: "沙烏地阿拉伯 Saudi Arabia" },
    { value: "SB", name: "索羅門群島 Solomon Islands" },
    { value: "SC", name: "塞席爾 Seychelles" },
    { value: "SD", name: "蘇丹 Sudan" },
    { value: "SE", name: "瑞典 Sweden" },
    { value: "SG", name: "新加坡 Singapore" },
    { value: "SH", name: "聖赫勒拿 Saint Helena" },
    { value: "SI", name: "斯洛維尼亞 Slovenia" },
    { value: "SJ", name: "斯瓦爾巴尖棉 Svalbard and Jan Mayen" },
    { value: "SK", name: "斯洛伐克 Slovakia" },
    { value: "SL", name: "獅子山 Sierra Leone" },
    { value: "SM", name: "聖馬利諾 San Marino" },
    { value: "SN", name: "塞內加爾 Senegal" },
    { value: "SO", name: "索馬利亞 Somalia" },
    { value: "SR", name: "蘇利南 Suriname" },
    { value: "ST", name: "聖多美普林西比 Sao Tome and Principe" },
    { value: "SV", name: "薩爾瓦多 El Salvador" },
    { value: "SY", name: "敘利亞 Syrian Arab Republic" },
    { value: "SZ", name: "史瓦濟蘭 Swaziland" },
    { value: "TC", name: "托克斯寇克斯群島 Turks and Caicos Islands" },
    { value: "TD", name: "查德 Chad" },
    { value: "TF", name: "法屬南部屬地 French Southern Territories" },
    { value: "TG", name: "多哥 Togo" },
    { value: "TH", name: "泰國 Thailand" },
    { value: "TJ", name: "塔吉克 Tajikistan" },
    { value: "TK", name: "托克勞 Tokelau" },
    { value: "TL", name: "東帝汶 Timor-Leste" },
    { value: "TM", name: "土庫曼 Turkmenistan" },
    { value: "TN", name: "突尼西亞 Tunisia" },
    { value: "TO", name: "東加 Tonga" },
    { value: "TR", name: "土耳其 Turkey" },
    { value: "TT", name: "千里達托貝哥 Trinidad and Tobago" },
    { value: "TV", name: "吐瓦魯 Tuvalu" },
    { value: "TW", name: "台灣 Taiwan" },
    { value: "TZ", name: "坦尚尼亞 Tanzania" },
    { value: "UA", name: "烏克蘭 Ukraine" },
    { value: "UG", name: "烏干達 Uganda" },
    { value: "UM", name: "美屬邊疆群島 United States Minor Outlying Islands" },
    { value: "US", name: "美國 United States" },
    { value: "UY", name: "烏拉圭 Uruguay" },
    { value: "UZ", name: "烏茲別克 Uzbekistan" },
    { value: "VA", name: "教廷(梵蒂岡) Holy See (Vatican City State)" },
    { value: "VC", name: "聖文森 Saint Vincent and The Grenadines" },
    { value: "VE", name: "委內瑞拉 Venezuela" },
    { value: "VG", name: "英屬維爾京群島 Virgin Islands, British" },
    { value: "VI", name: "美屬維京群島 Virgin Islands, U.S." },
    { value: "VN", name: "越南 Viet Nam" },
    { value: "VU", name: "萬那杜 Vanuatu" },
    { value: "WF", name: "華里斯福他納 Wallis and Futuna" },
    { value: "WS", name: "薩摩亞 Samoa" },
    { value: "YE", name: "葉門 Yemen" },
    { value: "YT", name: "美亞特 Mayotte" },
    { value: "ZA", name: "南非 South Africa" },
    { value: "ZM", name: "尚比亞 Zambia" },
    { value: "ZW", name: "辛巴威 Zimbabwe" },
  ];
};
